Reverted to old check workflows

diff --git a/.github/workflows/check-standard.yaml b/.github/workflows/check-standard.yaml
--- a/.github/workflows/check-standard.yaml
+++ b/.github/workflows/check-standard.yaml
@@ -31,33 +31,46 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Install JAGS
-        run: |
-          if [ "$RUNNER_OS" == "Linux" ]; then
-            sudo apt-get update && sudo apt-get install -y jags
-          elif [ "$RUNNER_OS" == "macOS" ]; then
-            brew install jags
-          fi
-        shell: bash
-
-      - name: Install JAGS (Windows)
+      # Install JAGS for Windows
+      - name: Install JAGS for Windows
         if: runner.os == 'Windows'
         run: |
-          curl.exe -o wjags.exe --url https://deac-fra.dl.sourceforge.net/project/mcmc-jags/JAGS/4.x/Windows/JAGS-4.2.0-Rtools33.exe
-          wjags.exe /S
+          curl.exe -L -o wjags.exe https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
+          .\wjags.exe /S
           del wjags.exe
+          echo "Checking JAGS installation..."
+          jags --version || echo "JAGS installation failed!"
         shell: cmd
 
-      - name: Build and Install JAGS on macOS (arm64)
+      # Install JAGS for macOS
+      - name: Install JAGS for macOS
         if: matrix.config.os == 'macos-latest'
         run: |
-          brew install gcc
-          curl -L -o jags-4.2.0.tar.gz https://deac-fra.dl.sourceforge.net/project/mcmc-jags/JAGS/4.x/Windows/JAGS-4.2.0-Rtools33.exe
-          tar -xzf jags-4.2.0.tar.gz
-          cd JAGS-4.2.0
-          ./configure --build=aarch64-apple-darwin
-          make
-          sudo make install
+          set -e
+          if [[ "$(uname -m)" == "arm64" ]]; then
+            echo "Building JAGS from source for macOS-arm64."
+            brew install gcc
+            curl -L -o jags-4.3.1.tar.gz https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/JAGS-4.3.1.tar.gz/download
+            tar -xzf jags-4.3.1.tar.gz
+            cd JAGS-4.3.1
+            ./configure --build=aarch64-apple-darwin
+            make
+            sudo make install
+            cd ..
+          else
+            brew update
+            brew install jags
+          fi
+          echo "Checking JAGS installation..."
+          jags --version || (echo "JAGS installation failed!" && exit 1)
+
+      # Install JAGS for Ubuntu
+      - name: Install JAGS for Ubuntu
+        if: matrix.config.os == 'ubuntu-latest'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jags
+          echo "Checking JAGS installation..."
           jags --version || echo "JAGS installation failed!"
 
       - uses: r-lib/actions/setup-pandoc@v2
