Updated windows and macos

diff --git a/.github/workflows/check-standard.yaml b/.github/workflows/check-standard.yaml
--- a/.github/workflows/check-standard.yaml
+++ b/.github/workflows/check-standard.yaml
@@ -35,15 +35,12 @@ jobs:
       - name: Install JAGS for Windows
         if: runner.os == 'Windows'
         run: |
-          # Download and install JAGS
           curl.exe -L -o wjags.exe https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
           .\wjags.exe /S
           del wjags.exe
 
-          # Add JAGS to the PATH
           set "PATH=%PATH%;C:\Program Files\JAGS\JAGS-4.3.1\bin"
 
-          # Verify JAGS installation
           echo "Checking JAGS installation..."
           jags --version || (echo "JAGS installation failed!" && exit 1)
         shell: cmd
@@ -61,18 +58,20 @@ jobs:
             # Install the package
             sudo installer -pkg JAGS-4.3.2.pkg -target /
 
-            # Verify the installation
-            echo "Checking JAGS installation..."
-            jags --version || (echo "JAGS installation failed!" && exit 1)
           else
             echo "Using Homebrew for JAGS installation on macOS Intel."
             brew update
             brew install jags
-
-            # Verify the installation
-            echo "Checking JAGS installation..."
-            jags --version || (echo "JAGS installation failed!" && exit 1)
           fi
+
+      # Install JAGS for Ubuntu
+      - name: Install JAGS for Ubuntu
+        if: matrix.config.os == 'ubuntu-latest'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jags
+          echo "Checking JAGS installation..."
+          jags --version || echo "JAGS installation failed!"
 
       - uses: r-lib/actions/setup-pandoc@v2
 
