recompiled documentation

diff --git a/.github/workflows/check-standard.yaml b/.github/workflows/check-standard.yaml
--- a/.github/workflows/check-standard.yaml
+++ b/.github/workflows/check-standard.yaml
@@ -43,8 +43,22 @@ jobs:
       - name: Install JAGS (Windows)
         if: runner.os == 'Windows'
         run: |
-          choco install jags -y
+          curl.exe -o wjags.exe --url https://deac-fra.dl.sourceforge.net/project/mcmc-jags/JAGS/4.x/Windows/JAGS-4.2.0-Rtools33.exe
+          wjags.exe /S
+          del wjags.exe
         shell: cmd
+
+      - name: Build and Install JAGS on macOS (arm64)
+        if: matrix.config.os == 'macos-latest'
+        run: |
+          brew install gcc
+          curl -L -o jags-4.2.0.tar.gz https://deac-fra.dl.sourceforge.net/project/mcmc-jags/JAGS/4.x/Windows/JAGS-4.2.0-Rtools33.exe
+          tar -xzf jags-4.2.0.tar.gz
+          cd JAGS-4.2.0
+          ./configure --build=aarch64-apple-darwin
+          make
+          sudo make install
+          jags --version || echo "JAGS installation failed!"
 
       - uses: r-lib/actions/setup-pandoc@v2
 
